### ISSUE TITLE
Queries for transcriptomic data

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_connect#104]
Proposed generic query from class with optional restriction on gene label (semantic tag)

```cypher
MATCH (g:Gene)<-[e:expresses]-(clus:Cluster)
-[:composed_primarily_of]->(c2)-[:SUBCLASSOF*0..]->(c1:Neuron)
WHERE 'Acetylcholine_receptor' in labels(g)
AND c1.label = 'distal medullary amacrine neuron'
OPTIONAL MATCH (clus)-[:has_source]->(ds:DataSet)
OPTIONAL MATCH (ds)-[:has_reference]->(p:pub)
OPTIONAL MATCH (ds)-[dbx:database_cross_reference]->(s:Site)
RETURN
c2.label, c2.short_form,
p.miniref[0] as ref,
g.label,
g.short_form,
apoc.coll.subtract(labels(g), ['Class', 'Entity', 'hasScRNAseq', 'Feature', 'Gene']) AS function,
e.expression_extent[0] as extent,
e.expression_level[0] as level
order by c2.label, g.label
```
vars  = c1.label.  Optionally add restriction on gene label (semantic tag) otherwise no filter

|c2.label|c2.short_form|ref|g.label|g.short_form|function|extent|level|
|---|---|---|---|---|---|---|---|
|distal medullary amacrine neuron Dm8|FBbt_00013774|Li et al., 2022, Science 375(6584): eabk2432|nAChRα6|FBgn0032151|[Acetylcholine_receptor,Ion_channel]|0.931034|2921.238|
|distal medullary amacrine neuron Dm8|FBbt_00013774|Li et al., 2022, Science 375(6584): eabk2432|nAChRβ1|FBgn0000038|[Acetylcholine_receptor,Ion_channel]|0.724138|2063.5767|
|distal medullary amacrine neuron Dm8|FBbt_00013774|Li et al., 2022, Science 375(6584): eabk2432|nAChRα1|FBgn0000036|[Acetylcholine_receptor,Ion_channel]|0.62069|1324.8326|
|distal medullary amacrine neuron Dm8|FBbt_00013774|Li et al., 2022, Science 375(6584): eabk2432|nAChRα7|FBgn0086778|[Acetylcholine_receptor,Ion_channel]|0.517241|1581.308|
|distal medullary amacrine neuron Dm8|FBbt_00013774|Li et al., 2022, Science 375(6584): eabk2432|nAChRα5|FBgn0028875|[Acetylcholine_receptor,Ion_channel]|0.896552|2000.6556|
|distal medullary amacrine neuron Dm9|FBbt_00111271|Li et al., 2022, Science 375(6584): eabk2432|nAChRα7|FBgn0086778|[Acetylcholine_receptor,Ion_channel]|0.878788|3116.4692|
|distal medullary amacrine neuron Dm9|FBbt_00111271|Li et al., 2022, Science 375(6584): eabk2432|nAChRβ1|FBgn0000038|[Acetylcholine_receptor,Ion_channel]|0.712121|1744.3744|

We could support this for individuals too, although there is a danger of it going via super-general classes used in annotation, e.g. 'adult neuron'.  OTOH, if we return the class, maybe that's OK.

```cypher
MATCH (g:Gene)<-[e:expresses]-(clus:Cluster)
-[:composed_primarily_of]->(c2)<-[:INSTANCEOF]-(c1:Neuron:Individual)
WHERE 'Acetylcholine_receptor' in labels(g)
AND c1.label = 'LC4 (FlyEM-HB:1907510214)'
OPTIONAL MATCH (clus)-[:has_source]->(ds:DataSet)
OPTIONAL MATCH (ds)-[:has_reference]->(p:pub)
OPTIONAL MATCH (ds)-[dbx:database_cross_reference]->(s:Site)
RETURN
c2.label, c2.short_form,
p.miniref[0] as ref,
g.label,
g.short_form,
apoc.coll.subtract(labels(g), ['Class', 'Entity', 'hasScRNAseq', 'Feature', 'Gene']) AS function,
e.expression_extent[0] as extent,
e.expression_level[0] as level
order by c2.label, g.label
```

We need a discovery method for gene (function) labels.  Not sure how to write the cypher - needs to aggregate multiple returned lists into a single uniq'd lists.  Here's a non-aggregating version

```cypher
MATCH (g:Gene) return distinct apoc.coll.subtract(labels(g), ['Class', 'Entity', 'hasScRNAseq', 'Feature', 'Gene'])
```

Maybe easier to just do in Python.

**Comment by dosumis** [comment]
Spec for addition to VFB_connect

**transcriptomic profile query**
1. Method on cross_server_tools
2. Method name: get_transcriptomic_profile - works only for class.
3. Args: cell_type: Takes class name, ID or symbol
4. KWARGS: function (gene type?) - takes one semantic tag on a gene.

**Query for gene functions**

1. Method on cross_server_tools
2. Method name: get_gene_function_filters
3. No args

**Comment by Clare72** [comment]
should we be returning cluster or sample names or something? - sometimes there are multiple rows for the same cell type/gene/pub combo and it is not immediately clear to users that this is because they are different samples

**Comment by Clare72** [comment]
they are different results with slightly different level/extent, so not a bug, but maybe confusing without making clear that they are different samples
