### ISSUE TITLE
feature request: method to get a list of all datasets

### ISSUE THREAD

**Issue by schlegelp** [VirtualFlyBrain/VFB_connect#129]
This would be useful to find whatever goes into `VfbConnect.get_instances_by_dataset`. For example "Xu2020NeuronsV1point1" for hemibrain neurons.

Something like `VfbConnect.get_datasets` maybe? Should probably include name + short description, if possible.

**Comment by Robbie1977** [comment]
```
from vfb_connect import vfb
vfb.get_datasets()
```
| Index | Label                                              | Symbol               | ID                       | Tags                                         | MiniRef                                           | FlyBase    | PMID    | DOI                          |
|-------|----------------------------------------------------|----------------------|--------------------------|----------------------------------------------|--------------------------------------------------|------------|---------|-----------------------------|
| 0     | Male Adult Nerve Cord (MANC) connectome neurons    | Takemura2023         | Entity                   | DataSet|Individual|has_image              | Takemura et al., 2023                             |            |         | 10.1101/2023.06.05.543757   |
| 1     | Grooming neurons and drivers (Hampel 2015)         | Hampel2015           | Entity                   | DataSet|Individual|has_image              | Hampel et al., 2015, eLife 4: e08758             | FBrf0229838| 26344548| 10.7554/eLife.08758         |
| 2     | LexA driver targeting mechanosensory eye bristles  | Hampel2017           | Entity                   | DataSet|Individual|has_image              | Hampel et al., 2017, eLife 6: e28804             | FBrf0236775| 28887878| 10.7554/eLife.28804         |
| 3     | Split-GAL4 lines from Takagi et al., 2017          | SplitTakagi2017      | Entity                   | DataSet|Individual                      | Takagi et al., 2017, Neuron 96(6): 1373--1387.e6 | FBrf0237618| 29198754| 10.1016/j.neuron.2017.10.030|
| 4     | split-GAL4 lines for descending neurons (Namiki...)| Namiki2018           | Entity                   | DataSet|Individual|has_image              | Namiki et al., 2018, eLife 7: e34272             | FBrf0239335| 29943730| 10.7554/eLife.34272         |
| ...   |                                                    |                      |                          |                                              |                                                  |            |         |                             |
| 161   | Split-GAL4 lines from Longden et al., 2023         | SplitLongden2023     | Entity                   | DataSet|Individual                      |                                                  |            |         |                             |
| 162   | EM FAFB Bates and Schlegel et al 2020              | BatesSchlegel2020    | Entity                   | DataSet|Individual|has_image|FAFB         | Bates and Schlegel et al., 2020                 |            |         | 10.1016/j.cub.2020.06.042   |
| 163   | Split-GAL4 lines from Turner-Evans et al., 2017    | SplitTurner_Evans2017| Entity                   | DataSet|Individual                      | Turner-Evans et al., 2017, eLife 6: e23496       | FBrf0235609| 28530551| 10.7554/eLife.23496         |
| 164   | Split-GAL4 lines from Turner-Evans et al., 2020    | SplitTurner_Evans2020| Entity                   | DataSet|Individual|has_image              | Turner-Evans et al., 2020, Neuron 108(1): 145-...| FBrf0246945| 32916090| 10.1016/j.neuron.2020.08.006|
| 165   | EM FAFB Baltruschat et al 2021                     | Baltruschat2021      | Entity                   | DataSet|Individual|has_image|FAFB         | Baltruschat et al., 2021, Cell Rep. 34(11): 10...| FBrf0248487| 33730583| 10.1016/j.celrep.2021.108871|
