### ISSUE TITLE
vfb.term - optionally restrict by gross type

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_connect#168]
Matching on labels, symbols and exact synonyms across a wide range of types can => confusing results:

![image](https://github.com/user-attachments/assets/596d324c-ef10-4a75-b8ca-efc2f76b8786)
![image](https://github.com/user-attachments/assets/fde76564-91e4-4965-9634-e9f13fa41c0f)

![image](https://github.com/user-attachments/assets/6947eaec-ddca-4ee2-830b-a82f9e72b262)

Maybe we could add the possibility to filter on gross types:  Class:Individual:Cell:Gene:Anatomy etc ?  Or mirror the filters on the main search on VFB?

**Comment by Robbie1977** [comment]
DL1 is the exact match for gene so we think this will hold but added vfb.search with tag filtering to allow refined searches
