### ISSUE TITLE
EPIC: Build API wrapper for VFB_connect

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_connect#32]
We need a REST API wrapper for [VFB_connect](https://github.com/VirtualFlyBrain/VFB_connect) with a [Swagger front end](https://swagger.io/).

Outline spec: 

 Endpoint | ARGS | method
 -- | -- | --
get_term_info | ID_list:list(String), Type: String (Optional, default: 'Entity'), Filter: String (Optional) | vc.neo_query_wrapper._get_term_info(ID_list, typ = Type)
get_subclasses | query:string, Filter (Optional) |  vc.get_subclasses(query)
get_instances | query, Filter (Optional) |  vc.get_Instances(query)
get_dbs |  (No Args) |  vc.neo_query_wrapper.get_dbs()
get_term_info_by_xref |  accessions, DB(optional), Filter(Optional) | vc.neo_query_wrapper.get_terms_by_xref(accessions, db=DB)
get_xrefs | ID_list , db(optional) |  vc.neo_query_wrapper.xref_2_vfb_id(ID_list, db=DB)
get_ids_by_xref | acc_list, db(optional) | vc.neo_query_wrapper.vfb_id_2_xrefs(acc_list, db=DB) 

Filters are functions applied to (TermInfo) output.  Development of this functionality is in progress.

Possibilities for architecture:

- [VFB_ingest_API](https://github.com/VirtualFlyBrain/vfb-data-ingest-api), 
- Very simple wrapper built as part of job applicant test:https://github.com/anitacaron/semantic_dev_tech_test

Note: This should be built to be easy to extend as VFB_connect is extended.

**Comment by hkir-dev** [comment]
Version1 released https://github.com/VirtualFlyBrain/VFB_connect_api
Missing items are:
-  get_term_info: How to use type and filter parameters?
-  get_subclasses: a sample usage (query string example). How to use filter
-  get_instances: How to use filters?
-  get_term_info_by_xref: How to use filters
