### ISSUE TITLE
template mismatch

### ISSUE THREAD

**Issue by YijieYin** [VirtualFlyBrain/VFB_connect#86]
Hi, it seems that some VFB object files registered to JRC2018U are actually in the JRC2010 space. I'm doing: 

```
vfb_id = "VFB_00020138"
vc = VfbConnect()
vcinfo = vc.neo_query_wrapper.get_anatomical_individual_TermInfo([vfb_id])
image_url = vcinfo[0]['channel_image'][0]['image']['image_folder'] + 'volume.obj'
print('point cloud located at: ', image_url)
```
Here are some sample urls: 
JFRC2:    https://v2.virtualflybrain.org/data/VFB/i/0002/0048/volume.obj
JRC2018   https://v2.virtualflybrain.org/data/VFB/i/0002/0048/VFB_00101567/volume.obj

2010: https://v2.virtualflybrain.org/data/VFB/i/0002/0032/volume.obj
2018: https://v2.virtualflybrain.org/data/VFB/i/0002/0032/VFB_00101567/volume.obj

If it doesn't have the 'VFB_xxxxxxxx' towards the end, then I know that it's from JFRC2/2010, and vice versa. But I think I'm supposed to get the .obj files from the 2018 template? It's not my code, and I don't see the brain space specified in the code. i'm wondering if it's the code or VFB. But in any case I don't think it should give me templates at random (though consistent within each vfb_id), which seems to be the case. Not sure if it's something to do with the .obj files? Here's a list of things I've collected in different templates: 

<google-sheets-html-origin><style type="text/css"></style>

vfb_id | 2010 | 2018 | http
-- | -- | -- | --
VFB_00020085 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0085/volume.obj
VFB_00020203 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0203/VFB_00101567/volume.obj
VFB_00020071 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0071/VFB_00101567/volume.obj
VFB_00020041 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0041/volume.obj
VFB_00020048 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0048/VFB_00101567/volume.obj
VFB_00020034 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0034/VFB_00101567/volume.obj
VFB_00020010 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0010/volume.obj
VFB_00020065 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0065/VFB_00101567/volume.obj
VFB_00020100 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0100/volume.obj
VFB_00020219 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0219/volume.obj
VFB_00020232 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0232/VFB_00101567/volume.obj
VFB_00020052 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0052/volume.obj
VFB_00020059 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0059/VFB_00101567/volume.obj
VFB_00020000 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0000/VFB_00101567/volume.obj
VFB_00020094 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0094/VFB_00101567/volume.obj
VFB_00020093 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0093/VFB_00101567/volume.obj
VFB_00020230 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0230/VFB_00101567/volume.obj
VFB_00020089 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0089/volume.obj
VFB_00020052 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0052/volume.obj
VFB_00020051 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0051/volume.obj
VFB_00020030 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0030/volume.obj
VFB_00020063 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0063/VFB_00101567/volume.obj
VFB_00020060 | TRUE |   | http://www.virtualflybrain.org/data/VFB/i/0002/0060/volume.obj
VFB_00020035 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0035/VFB_00101567/volume.obj
VFB_00020044 |   | TRUE | http://www.virtualflybrain.org/data/VFB/i/0002/0044/VFB_00101567/volume.obj

**Comment by dosumis** [comment]
Many older images are available on multiple templates.

Please use vc.neo_query_wrapper.get_images() to get images of individual neurons on a specified template.  

https://vfb-connect.readthedocs.io/en/stable/API_reference.html#vfb_connect.neo.query_wrapper.QueryWrapper.get_images

- Or you can download directly from the VFB UI for single neurons or all images on the image browsers.

**Comment by YijieYin** [comment]
Hi, thanks for getting back to me so quickly. I tried running this, and got 
```
TypeError: get_images() missing 1 required positional argument: 'image_folder'
```
and I'm trying to do 
```
vcinfo = vc.neo_query_wrapper.get_images([vfb_id], template='JRC2018U')
```
So I'd like to save it to this variable, and not to the local folder. Is that possible? What image_folder would you recommend? Thank you!

**Comment by dosumis** [comment]
The image folder is just a path to where you'd like to save the image(s) locally.  When you say you want to save to a variable, do you just want the path?

**Comment by YijieYin** [comment]
Thanks. I think I just want the URL location.

**Comment by YijieYin** [comment]
Hello, please could you tell me how I can get the URL location? Thanks!

**Comment by dosumis** [comment]
There is no convenience method for this at present, but you can parse the JSON

This list comprehension generates a list of tuples with template & image URL.

```python
rom  vfb_connect.cross_server_tools import VfbConnect
vc = VfbConnect()
images = vc.neo_query_wrapper.get_TermInfo(['VFB_00020138'])[0]['channel_image']
[ (i['image']['template_channel']['label'], i['image']['image_folder']) for i in images ]
```

You could easily add a conditional to return only images on the desired template.

Note - you can also get the same JSON output for individuals(instances) with images from a variety of other queries, including by dataset (see `vc.get_instances_by_dataset()`), or by type (e.g. 'adult fruitless aSP-h (female) lineage clone'  see `vc.get_instances()`)

**Comment by YijieYin** [comment]
Hi, thanks a lot! This worked. And sorry for the delay in getting back to you. 

Just FYI, I guess this is the reason why I sometimes got the 2010 template and sometimes the 2018 one: 
The `images` object I get looks like this 
```
[{'image': {'template_channel': {'symbol': '',
    'iri': 'http://virtualflybrain.org/reports/VFBc_00017894',
    'types': ['Entity', 'Individual', 'Template', 'VFB'],
    'short_form': 'VFBc_00017894',
    'label': 'JFRC2_template_c'},
   'index': [],
   'template_anatomy': {'symbol': '',
    'iri': 'http://virtualflybrain.org/reports/VFB_00017894',
    'types': ['Entity',
     'Adult',
     'Anatomy',
     'Individual',
     'Nervous_system',
     'Template',
     'VFB',
     'has_image'],
    'short_form': 'VFB_00017894',
    'label': 'adult brain template JFRC2'},
   'image_folder': 'http://www.virtualflybrain.org/data/VFB/i/0002/0070/'},
  'channel': {'symbol': '',
   'iri': 'http://virtualflybrain.org/reports/VFBc_00020070',
   'types': ['Entity', 'Individual', 'VFB'],
   'short_form': 'VFBc_00020070',
   'label': 'VLPd_p1_02-c'},
  'imaging_technique': {'symbol': 'Confocal',
   'iri': 'http://purl.obolibrary.org/obo/FBbi_00000251',
   'types': ['Entity', 'Class'],
   'short_form': 'FBbi_00000251',
   'label': 'confocal microscopy'}},
 {'image': {'template_channel': {'symbol': '',
    'iri': 'http://virtualflybrain.org/reports/VFBc_00101567',
    'types': ['Entity', 'Individual', 'Template'],
    'short_form': 'VFBc_00101567',
    'label': 'JRC2018Unisex_c'},
   'index': [],
   'template_anatomy': {'symbol': '',
    'iri': 'http://virtualflybrain.org/reports/VFB_00101567',
    'types': ['Entity',
     'Adult',
     'Anatomy',
     'Individual',
     'Nervous_system',
     'Template',
     'has_image'],
    'short_form': 'VFB_00101567',
    'label': 'JRC2018Unisex'},
   'image_folder': 'http://www.virtualflybrain.org/data/VFB/i/0002/0070/VFB_00101567/'},
  'channel': {'symbol': '',
   'iri': 'http://virtualflybrain.org/reports/VFBc_00020070',
   'types': ['Entity', 'Individual', 'VFB'],
   'short_form': 'VFBc_00020070',
   'label': 'VLPd_p1_02-c'},
  'imaging_technique': {'symbol': 'Confocal',
   'iri': 'http://purl.obolibrary.org/obo/FBbi_00000251',
   'types': ['Entity', 'Class'],
   'short_form': 'FBbi_00000251',
   'label': 'confocal microscopy'}}]
```
I used to always get the first `image_folder` link. But sometimes the first one is from the 2010 template, sometimes the 2018 template. I did add a conditional and it worked, but just to let you know that the sequence isn't always the same :) 

Thanks!
